MentorApp/MentorApp/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mentorapp/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from userProfile import views
from match import views as matches_views

from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings


# from ml_endpoints.urls import urlpatterns as endpoints_urlpatterns


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login' ),
    path('logout/', views.logout_view , name="logout"),
    path('account_activation_sent/', views.account_activation_sent, name='account_activation_sent'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('profile/', views.profile, name='profile'),
    path('faq/', views.faq_page, name='faq' ),




    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='passwordReset/password_change_done.html'),
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='passwordReset/password_change.html'),
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordReset/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='passwordReset/password_reset_form.html'), name='password_reset'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='passwordReset/password_reset_complete.html'),
     name='password_reset_complete'),

    path("survey/", include("survey.urls")),

    path('nested_admin/', include('nested_admin.urls')),
    # path(r"^api/v1/", include('router.urls')),
    # path(r"^api/v1/", include('ml_endpoints.urls'))
    path('', include('ml_endpoints.urls')),
    path('admin/match/manualmatch', matches_views.manual_match, name='manual_match'),
    url('match-autocomplete_mentor/', matches_views.match_autocomplete_mentor, name='match-autocomplete_mentor'),
    url('match-autocomplete_student/', matches_views.match_autocomplete_student, name='match-autocomplete_student'),

    url('handle_manual/', matches_views.handle_manual, name='handle_manual'),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# urlpatterns += endpoints_urlpatterns

survey/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from survey.views import ConfirmView, IndexView, SurveyCompleted, SurveyDetail
from survey.views.survey_result import serve_result_csv
from survey.views.survey_result import serve_result_json

urlpatterns = [
    url(r"^$", IndexView.as_view(), name="survey-list"),
    url(r"^(?P<id>\d+)/", SurveyDetail.as_view(), name="survey-detail"),
    url(r"^csv/(?P<primary_key>\d+)/", serve_result_csv, name="survey-result-csv"),
    url(r"^json/(?P<primary_key>\d+)/", serve_result_json, name="survey-result-json"),
    url(r"^(?P<id>\d+)/completed/", SurveyCompleted.as_view(), name="survey-completed"),
    url(r"^(?P<id>\d+)-(?P<step>\d+)/", SurveyDetail.as_view(), name="survey-detail-step"),
    url(r"^confirm/(?P<uuid>\w+)/", ConfirmView.as_view(), name="survey-confirmation"),
]

userProfile/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .enums import *
from django.utils.translation import ugettext_lazy as _


class AdditionalQuestions(models.Model):
    name = models.CharField(max_length=1000,default='')
    # questions_count = models.IntegerField(default=0)
    #description = models.CharField(max_length=70)
    created = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    # slug = models.SlugField()
    #roll_out = models.BooleanField(default=False)
    class Meta:
        ordering = ['created',]
        verbose_name_plural ="Additional Questions"
    def __str__(self):
        return self.name

class Question(models.Model):
    question_form = models.ForeignKey(AdditionalQuestions, on_delete=models.CASCADE)
    label = models.CharField(max_length=1000)
    order = models.IntegerField(default=0)
    def __str__(self):
        return self.label

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    def __str__(self):
        return self.text


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_pic = models.ImageField(default='profileimage.png', null = True, blank=True)
    question_form = models.ForeignKey(AdditionalQuestions, on_delete=models.CASCADE, null = True)
    email_confirmed = models.BooleanField(default=False)
    first_name = models.CharField(max_length=30, default='')
    last_name = models.CharField(max_length=30, default='')
    phone = models.CharField(max_length = 15, blank=True, help_text='(000) 000-000')
    user_type = models.CharField(max_length = 20, choices=UserChoice.choices(), default = 'mentee')
    job_title = models.CharField(max_length=30, default='')
    company = models.CharField(max_length=30, default='')
    county = models.CharField(max_length = 20, choices=CountyChoice.choices(), default = '')
    gender_pronouns  = models.CharField(max_length = 20, choices=GenderChoice.choices(), default = '')
    ethnicity  = models.CharField(max_length = 20, choices=EthnicityChoice.choices(), default = '')
    education = models.CharField(max_length = 20, choices=EducationChoice.choices(), default = '')
    industry = models.CharField(max_length = 20, choices=IndustryChoice.choices(), default = '')
    learningtrack = models.CharField(max_length = 20, choices=TrackChoice.choices(), default = '')
    linkedin = models.URLField(max_length = 60, default = '')
    funfact = models.CharField(max_length=100, default='')
    cohort = models.CharField(max_length = 20, choices=CohortChoice.choices(), default = '')
    site_location = models.CharField(max_length = 20, choices=SiteChoice.choices(), default = '')
    # x = models.FloatField()
    # y = models.FloatField()
    # width = models.FloatField()
    # height = models.FloatField()

    def __str__(self):
        return self.user.username


class Response(models.Model):
    question_form = models.ForeignKey(AdditionalQuestions, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, null = True)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    answer = models.ForeignKey(Answer,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.question.label


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()

class FrequentlyAsked(models.Model):
    question = models.CharField(max_length=1000, default='')
    answer = models.TextField(max_length=5000, default='')
    class Meta:
        verbose_name_plural ="Frequently Asked Questions Mentee"
    def __str__(self):
        return self.question

class FrequentlyAskedMentor(models.Model):
    mentor_questions = models.CharField(max_length=1000, default='')
    mentor_answers = models.TextField(max_length=5000, default='')
    class Meta:
        verbose_name_plural="Frequently Asked Questions Mentor"
    def __str__(self):
        return self.mentor_questions

class Email(models.Model):
    from_email = models.CharField(max_length=1000, default='')
    to_email = models.CharField(max_length=20000, default='', blank=True)
    email_mentors = models.BooleanField(default=False, verbose_name=_('Email All Mentors'))
    email_mentees = models.BooleanField(default=False, verbose_name=_('Email All Mentees'))
    cc_to_email = models.CharField(max_length=20000, default='', blank=True, verbose_name=_('CC:'))
    cc_email_mentors = models.BooleanField(default=False, verbose_name=_('CC All Mentors'))
    cc_email_mentees = models.BooleanField(default=False, verbose_name=_('CC All Mentees'))
    bcc_to_email = models.CharField(max_length=20000, default='', blank=True, verbose_name=_('BCC:'))
    bcc_email_mentors = models.BooleanField(default=False, verbose_name=_('BCC All Mentors'))
    bcc_email_mentees = models.BooleanField(default=False, verbose_name=_('BCC All Mentees'))
    subject = models.CharField(max_length=5000, default='')
    message_email = models.TextField(max_length=30000, default='')

class MatchProfile(models.Model):
    match_user = models.OneToOneField(Profile, on_delete=models.CASCADE, null = True)
    def __str__(self):
        return str(self.match_user.user_id)

class CustomNotifications(models.Model):
    title = models.CharField(max_length=1000, default='')
    notify_mentors = models.BooleanField(default=False, verbose_name=_('Notify All Mentors'))
    notify_mentees = models.BooleanField(default=False, verbose_name=_('Notify All Mentees'))
    message = models.TextField(max_length=5000, default='')    

userProfile/forms.py
from PIL import Image
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Profile
from django.core.files import File

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Please provide a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )
        managed = True

class ProfileForm(forms.ModelForm):

    #defining variables for cropping the image
    x = forms.FloatField(widget=forms.HiddenInput(), required = False, label ="")   #x coordinate of where the cropfield is
    y = forms.FloatField(widget=forms.HiddenInput(), required = False, label ="")   #y coordinate of where cropfield is
    width = forms.FloatField(widget=forms.HiddenInput(), required = False, label ="")    #width of cropbox
    height = forms.FloatField(widget=forms.HiddenInput(), required = False, label ="")   #heigh of cropbox

    class Meta:
        model = Profile
        phone = model.phone
        fields = ('first_name', 'last_name','profile_pic', 'phone', 'user_type','job_title','company','county','county','gender_pronouns','ethnicity','education','industry','learningtrack','linkedin','funfact', 'x', 'y', 'width', 'height' )
    def __init__(self, *args, **kwargs):
            super(ProfileForm, self).__init__(*args, **kwargs)
            self.fields['x'].required = False
            self.fields['y'].required = False
            self.fields['width'].required = False
            self.fields['height'].required = False
            for field in iter(self.fields):
                if field is not 'profile_pic':
                    self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })




    #saving values of x,y,w,h of the photo that user uploads
    #implementation is for the cropper box
    def save(self):
        photo = super(ProfileForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        # if x, y, w, and h have a value, then update the photo
        # if statement will run if the
        if x or y or w or h:
            image = Image.open(photo.profile_pic)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
            resized_image.save(photo.profile_pic.path)

        return photo

userProfile/templates/pages/edit_profile.html
{% extends 'base.html' %}
{% load static%}
{% block extrajs %}
<script>



  function popitup() {
    var modal = document.getElementById("myModal");
    modal.style.display = "block";
  }

  function editProfileAlert() {
    alert('Please save changes to your profile!')
  }

  // Get the button that opens the modal
  var modal = document.getElementById("myModal");

  // Get the <span> element that closes the modal
  var span = document.getElementsByClassName("close")[0];

  // When the user clicks on <span> (x), close the modal
  span.onclick = function () {
    modal.style.display = "none";
  }

  // When the user clicks anywhere outside of the modal, close it
  window.onclick = function (event) {
    if (event.target == modal) {
      modal.style.display = "none";
    }
  }

  window.reload = function (event) {
    if (event.target == modal) {
      modal.style.display = "block";
    }
  }

  $(function () {

    /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
    $("#id_profile_pic").change(function () {
      if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
          $("#image").attr("src", e.target.result);
          $("#modalCrop").modal("show");
        }
        reader.readAsDataURL(this.files[0]);
      }
    });

    /* SCRIPTS TO HANDLE THE CROPPER BOX */
    var $image = $("#image");
    var cropBoxData;
    var canvasData;
    $("#modalCrop").on("shown.bs.modal", function () {
      $image.cropper({
        viewMode: 1,
        aspectRatio: 1 / 1,
        minCropBoxWidth: 200,
        minCropBoxHeight: 200,
        ready: function () {
          $image.cropper("setCanvasData", canvasData);
          $image.cropper("setCropBoxData", cropBoxData);
        }
      });
    }).on("hidden.bs.modal", function () {
      cropBoxData = $image.cropper("getCropBoxData");
      canvasData = $image.cropper("getCanvasData");
      $image.cropper("destroy");
    });

    /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
    $(".js-crop-and-upload").click(function () {
      var cropData = $image.cropper("getData");
      $("#id_x").val(cropData["x"]);
      $("#id_y").val(cropData["y"]);
      $("#id_height").val(cropData["height"]);
      $("#id_width").val(cropData["width"]);
      // $("#formUpload").submit();
    });

  });
</script>
{% endblock %}

{% block content %}
<link href="{% static 'survey/css/bootstrap.min.css' %}" rel="stylesheet">
<!--cropper lib -->
<div class="viewbox">

  <div class="column">

    <div class="column-header">
      <h4>{{user.profile.first_name}}'s Profile</h4>
    </div>
    <div class="tabs">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab"
          aria-controls="v-pills-home" aria-selected="true"><i class="far fa-user"></i> Personal Info </a>
        <a class="nav-link" id="v-pills-profile-tab" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile"
          aria-selected="false" onclick="editProfileAlert()"><i style="margin-left:-35px" class="fas fa-cog"></i>
          Settings</a>
        <a class="nav-link" id="v-pills-settings-tab" href="#v-pills-settings" role="tab"
          aria-controls="v-pills-settings" aria-selected="false" onclick="editProfileAlert()"><i
            style="margin-left:-35px" class="fas fa-info"></i> Matches</a>
        <a class="nav-link" id="v-pills-survey-tab" href="#v-pills-survey" role="tab" aria-controls="v-pills-survey"
          aria-selected="false" onclick="editProfileAlert()"><i style="margin-left:-35px" class="fas fa-file"></i>
          Surveys</a>
      </div>
    </div>
  </div>


  <form class="profileinfo" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class='profileHeader'>
      <div id="profileimg">
        <img src='{{request.user.profile.profile_pic.url}}'>
        <button type="button" class="icon-buton" onclick="popitup()"><i class="fas fa-pen"></i></button>
      </div>
    </div>
    <div class="container">
      <div class="row">
        {% for field in profile_form%}
        {% if field.name != 'profile_pic' %}
        <div class="col-sm-6 edit">
          {{ field.label }}

          {{ field }}

        </div>
        {% endif %}

        {% endfor %}
      </div>

    </div>

    <!-- The Modal -->
    <div id="myModal" class="modal">

      <!-- Modal content -->
      <div class="modal-content">
        <span class="close">&times;</span>
        <div id="profileimg">
          <img src="{{ profile_form.instance.profile_pic.url }}" />
          <p>{{ profile_form.profile_pic}}</p>
        </div>
      </div>

    </div>

    <div class="modal fade" id="modalCrop">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title">Crop the photo</h4>
          </div>
          <div class="modal-body">
            <img src="" id="image" style="max-width: 100%;">
          </div>
          <div class="modal-footer">
            <div class="btn-group pull-left" role="group">
            </div>
            <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
            <button type="button" class="btn btn-primary js-crop-and-upload" data-dismiss="modal">Crop and
              upload</button>
          </div>
        </div>
      </div>
    </div>
    <button type="submit" class="savebutton">Save Changes</button>
  </form>


</div>




{% endblock %}

userProfile/templates/pages/export.html
{% extends 'base.html' %}

{% block content %}
<h3>Export Data</h3>
<p>exporting from database</p>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Please select format of file.</p>
    <select name="file-format" class="form-control my-3">
        <option selected>Choose format...</option>
        <option>CSV</option>
        <option>JSON</option>
        <option>XLS (Excel)</option>
      </select>
    <button class="btn btn-primary" type="submit">Export</button>
  </form>
  <a href="{% url 'home' %}">Return Home View</a>
  {% endblock %} 

userProfile/templates/pages/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="row" id="homeMediaCSS">
	<div class="col-8">
		<div class="welcome">
			<h2>Welcome, {{ user.profile.first_name }}!</h2> <br>
			<h6>Congratulations on getting selected for this Mentor Program. We hope you learn and develop
				professional skills for your career and grow with your match!</h6> <br><br>
			<h6>Please be sure to complete your profile on the profile page and any surveys shown on the
				right so we can match you to the right people!</h6>
		</div>

		<div class="notification-center">
			<h4>Notification Center

				{% for survey in active %}
				<span class="badge">{{length}}</span> 
				{% if length == 0 %}
				<br> <br>
				<h5 class="surveys-complete">You have completed all surveys!</h5>
				{% endif %}
				{% endfor %}  
				
			</h4>
			<div class="row">

				{% for not in notify %}
				<div class="col-sm-4">
						<div class="notification">
							<p class="survey-text">{{not.title}} <br> {{not.message}}</p>
						</div>
				</div>
				{% endfor %}

				{% for survey in surveys %}
				<div class="col-sm-4">
					<a href="/survey/{{survey.id}}">
						<div class="notification">
							<p class="survey-text">{{survey.name}} <br> Click here to take the survey</p>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>

	</div>

	<div class="col-4">
		<br>
		{% if match != 0 %}
		<h3 style="text-align: center;">Congratulations! You've got a match!</h3> <br>
		<div class='matchprofile'>
			<div id="profileimghome"><img src='{{match.profile_pic.url}}' width="240"></div>
			<small>
				<h4>{{ match.first_name }} {{ match.last_name }}</h4>
				{{ match.user.email }}<br>
				{{ match.get_industry_display }}<br>
				{{ match.company }}<br>
				{{ match.job_title }}
			</small>
		</div>

		{% else %}
		<br> <br>
		<h5 id="profileimghome">You don't have a match... yet!</h5>
		{% endif %}
	</div>

</div>
{% endblock %}

userProfile/templates/pages/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% load i18n %}

<div class="viewbox">
  <div class="column">
    <div class="column-header">
      {% if user.profile.first_name %}
      <h4>{{user.profile.first_name}}'s Profile</h4>
      {% else %}
      <h4>{{user.username}}'s Profile</h4>
      {% endif %}
    </div>
    <div class="tabs">
      <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
        <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab"
          aria-controls="v-pills-home" aria-selected="true"><i class="far fa-user"></i> Personal Info </a>
        <a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab"
          aria-controls="v-pills-profile" aria-selected="false"><i style="margin-left:-35px" class="fas fa-cog"></i>
          Settings</a>
        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab"
          aria-controls="v-pills-settings" aria-selected="false"><i style="margin-left:-35px" class="fas fa-info"></i>
          Matches</a>
        <a class="nav-link" id="v-pills-survey-tab" data-toggle="pill" href="#v-pills-survey" role="tab"
          aria-controls="v-pills-survey" aria-selected="false"><i style="margin-left:-35px" class="fas fa-file"></i>
          Surveys</a>
      </div>
    </div>

  </div>

  <form class="profileinfo" method="get">


    <form class="profile_display" method="post">{% csrf_token %}
      {% csrf_token %}
      <div class="tab-content" id="v-pills-tabContent">
        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
          <div class="profileHeader">
            <div id="profileimg"><img src='{{request.user.profile.profile_pic.url}}' width="240" style="right:35%">
              <div class=" profileUserName">{{user.profile.first_name}}
                {{user.profile.last_name}} ({{user.username}})
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <h5>
                Username
              </h5>
              <p>
                {{ user.username }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Name
              </h5>
              <p>
                {{ user.profile.first_name }} {{ user.profile.last_name }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Preferred Pronouns
              </h5>
              <p>
                {{ user.profile.get_gender_pronouns_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Ethnicity
              </h5>
              <p>
                {{ user.profile.get_ethnicity_display }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                City
              </h5>
              <p>
                {{ user.profile.get_county_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                County
              </h5>
              <p>
                {{ user.profile.get_county_display }}</p>
            </div>
          </div>
          <hr>
          <h3>Contact Info</h3>
          <div class="row">
            <div class="col-sm-6">
              <h5>
                Phone
              </h5>
              <p><a href="tel:{{ user.profile.phone }}">+{{ user.profile.phone }}</a>
              </p>
            </div>
            <div class="col-sm-6">
              <h5>
                Email
              </h5>
              <p>
                <a href="mailto:{{ user.email}}">{{ user.email}}</a></p>
            </div>
          </div>
          <hr>
          <h3>Professional Info</h3>
          <div class="row">
            <div class="col-sm-6">
              <h5>
                Company
              </h5>
              <p>
                {{ user.profile.company }}</p>
            </div>

            <div class="col-sm-6">
              <h5>
                Job Title
              </h5>
              <p>
                {{ user.profile.job_title }} </p>
            </div>

            <div class="col-sm-6">
              <h5>
                Industry
              </h5>
              <p>
                {{ user.profile.get_industry_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Education
              </h5>
              <p>
                {{ user.profile.get_education_display }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Learning Track
              </h5>
              <p>
                {{ user.profile.get_learningtrack_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                LinkedIn
              </h5>
              <p>
                <a href={{ user.profile.linkedin }} target="_blank">{{ user.profile.linkedin }}</a></p>
            </div>
            <div class="col-sm-6">
              <h5>
                Fun Fact
              </h5>
              <p>
                {{ user.profile.funfact}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Cohort
              </h5>
              <p>
                {{ user.profile.cohort}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Site Location
              </h5>
              <p>
                {{ user.profile.site_location}}</p>
            </div>
          </div>

          <button type="button" class="editbutton" onclick="parent.location= '/edit_profile/'" id="enter">Edit
            Profile</button>
        </div>

        <div class="tab-pane fade" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
          <h3>Settings</h3>
          <iframe src="/password_change/" class="iframe"></iframe>
        </div>

        <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">
          {% if match != 0 %}
          <h3>Congratulations! You've got a match!</h3>
          <div class="profileHeader">
            <div id="profileimg"><img src='{{match.profile_pic.url}}' width="240" style="right:35%">
              <div class=" profileUserName">{{match.first_name}}
                {{match.last_name}} ({{match.user.username}})
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-sm-6">
              <h5>
                Username
              </h5>
              <p>
                {{ match.user.username }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Name
              </h5>
              <p>
                {{ match.first_name }} {{ match.last_name }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Preferred Pronouns
              </h5>
              <p>
                {{ match.get_gender_pronouns_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Ethnicity
              </h5>
              <p>
                {{ match.get_ethnicity_display }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                City
              </h5>
              <p>
                {{ match.get_county_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                County
              </h5>
              <p>
                {{ match.get_county_display }}</p>
            </div>
          </div>
          <hr>
          <h3>Contact Info</h3>
          <div class="row">
            <div class="col-sm-6">
              <h5>
                Phone
              </h5>
              <p><a href="tel:{{ match.phone }}">+{{ match.phone }}</a>
              </p>
            </div>
            <div class="col-sm-6">
              <h5>
                Email
              </h5>
              <p>
                <a href="mailto:{{ match.user.email}}">{{ match.user.email}}</a></p>
            </div>
          </div>
          <hr>
          <h3>Professional Info</h3>
          <div class="row">
            <div class="col-sm-6">
              <h5>
                Company
              </h5>
              <p>
                {{ match.company }}</p>
            </div>

            <div class="col-sm-6">
              <h5>
                Job Title
              </h5>
              <p>
                {{ match.job_title }} </p>
            </div>

            <div class="col-sm-6">
              <h5>
                Industry
              </h5>
              <p>
                {{ match.get_industry_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Education
              </h5>
              <p>
                {{ match.get_education_display }}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Learning Track
              </h5>
              <p>
                {{ match.get_learningtrack_display}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                LinkedIn
              </h5>
              <p>
                <a href={{ match.linkedin }} target="_blank">{{ match.linkedin }}</a></p>
            </div>
            <div class="col-sm-6">
              <h5>
                Fun Fact
              </h5>
              <p>
                {{ match.funfact}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Cohort
              </h5>
              <p>
                {{ match.cohort}}</p>
            </div>
            <div class="col-sm-6">
              <h5>
                Site Location
              </h5>
              <p>
                {{ match.site_location}}</p>
            </div>
          </div>
          {% else %}
          <br> <br>
          <h5 id="profileimghome">You don't have a match... yet!</h5>
          {% endif %}
        </div>

        <div class="tab-pane fade" id="v-pills-survey" role="tabpanel" aria-labelledby="v-pills-survey-tab">
          <h3>Past Surveys</h3> <br>
          <div id="pastsurveys">
            {% for survey in allsurveys %}
            <li><a id="links" href="{{ survey.get_absolute_url }}">{% trans "Edit your survey response for"%}
                {{survey.name}}</a></li>
            {% endfor %}
          </div>
        </div>
      </div>
</div>


</form>

</form>

</div>

{% endblock content %}